### ISSUE TITLE
Configure wordsearch with dictionary/words file

### ISSUE THREAD

**Issue by GrimPixel** [ogallagher/wordsearch_generator#35]
There are a lot of datasets of dictionary available for free
https://polyglotclub.com/wiki/Language/Multiple-languages/Culture/Internet-Dictionaries

So I wish I could load a dictionary file (ideally DSV as described in https://github.com/ogallagher/wordsearch_generator/issues/34) with tens of thousands of entries and let the program select several entries randomly and generate the game.

**Comment by ogallagher** [comment]
Currently a wordsearch generator is configured with a JSON file, which can include a list of words (and clues).

To make it more convenient to control the word list, I'll add support for a separate words/dictionary file. The words file can be referenced within the config file instead of having the embedded words list, or selected in a later step (requiring external prompt/controls in the UI).

**Comment by ogallagher** [comment]
Current implementation for including a words file path in the config file seems to work with the cli driver. Remaining agenda before closing issue:

- [ ] cli: select words file in interactive mode
- [ ] webpage: add control to use words file instead of words form (works for both modes)
    - [ ] config file mode
    - [ ] config form more

**Comment by ogallagher** [comment]
> Mixing and matching config json and words dev files in the webpage

![wordsearch_webpage_config_words_mix_match](https://user-images.githubusercontent.com/17031438/150460766-77674a29-7dc7-45e5-ae2b-b75c8288eb37.png)
